### ISSUE TITLE
Latin and Cyrillic letters don't look like the same font (handwriting of the same person)

### ISSUE THREAD

**Issue by thorn0** [excalidraw/virgil#13]
The difference between some Cyrillic and Latin characters that could but don't look the same seems unjustified. The Latin glyphs almost in every such case look better to me. The Latin letters look streamlined and a bit more readable whereas Cyrillic look clumsy. I can elaborate in more detail if needed. I've used a dictionary to find some words that consist of those homoglyph letters to show what I mean (would be great if all the letters on the right looked exactly the same as on the left):

![image](https://user-images.githubusercontent.com/94334/83903021-1c359d80-a766-11ea-8a65-02bf4ec17a7a.png)

е у х ← these look the clumsiest, see also https://github.com/excalidraw/virgil/issues/12

Text for testing:
```
АЕІО ВСНКМРТХ
аеіоу сдтпргх

спірохета і гептахорд
подруга-реготуха
Аспарагус уперехрест
стереопара
відеопротест
```

**Comment by Yourownfont** [comment]
will continue tomorrow! /Ellinor

**Comment by thorn0** [comment]
Thanks! This issue is big and most probably should be decomposed into smaller issues, but if the Cyrillic letters eventually become as cool as the Latin ones, it'd be... well, really cool, I guess :)

**Comment by j-f1** [comment]
I do like the Cyrillic К more than the Latin K.

**Comment by thorn0** [comment]
<table><tr><td>

![image](https://user-images.githubusercontent.com/94334/110166984-c299f680-7dfd-11eb-9676-a6f6a7fe1a02.png)

<td>

(1) Cyrillic

(2) Latin

(3) Latin with the Cyrillic К

</table>

I don't know. The K in (3) doesn't look like it's from the same font to me. The lines seem a bit thinner than in the Latin letters. And the curve at the bottom right - the Latin letters in this font don't have such hooks.
