### ISSUE TITLE
Digit 1 looks confusing without other digits next to it

### ISSUE THREAD

**Issue by thorn0** [excalidraw/virgil#20]
It's not very readable on its own in captions like "Group 1" (indistinguishable from uppercase I, lowercase L). Captions like "Group 10" or "2019" are fine though.

I think it needs a serif.

Also, ideally, to preserve the spirit of the font, it might be possible to use ligatures to render 1 in its current shape next to other digits.

![image](https://user-images.githubusercontent.com/94334/109388130-e1841e80-790d-11eb-8686-a80d19b9b718.png)

**Comment by Yourownfont** [comment]
Hmm? 
![image](https://user-images.githubusercontent.com/61000413/110033132-476f0c80-7d39-11eb-9625-8a3deaa66b7d.png)
Looks weird - anyone with a better number 1? 

/Ellinor

**Comment by thorn0** [comment]
Agree, looks so-so.

Given that I and J have big horizontal serifs:
![image](https://user-images.githubusercontent.com/94334/110110144-146b5e00-7db7-11eb-9efb-853f294723e8.png)
can probably 1 have it too at the bottom?
