### ISSUE TITLE
Digit 2 could be a bit more legible and distinguishable from L

### ISSUE THREAD

**Issue by thorn0** [excalidraw/virgil#21]
`L2£Ł`
![image](https://user-images.githubusercontent.com/94334/109388228-8bfc4180-790e-11eb-9726-ec0bc36276e7.png)

**Comment by sansnom** [comment]
The "2" is the main reason (if not the only) why I switch to the other fonts (fearing people might not even recognize it). I've never really seen people writing "2" like this (but I'm not an expert :D).

**Comment by dwelle** [comment]
> [...] distinguishable from L

It's pretty distinguishable from `L`, but one could mistake it for `a`, at least Greek alpha `α`:

![image](https://user-images.githubusercontent.com/5153846/109551015-4edfad00-7ad0-11eb-9a28-d59ec37da48a.png)

> I've never really seen people writing "2" like this (but I'm not an expert :D).

In my peer group lots of people wrote it like that, but I agree that we should move to a traditional `2` symbol.

**Comment by j-f1** [comment]
I think if we switch to a traditional 2 we should make the | of the L more vertical so they can’t be confused. Or maybe curving the top of the 2 farther will be enough.

**Comment by thorn0** [comment]
> curving the top of the 2 farther will be enough.

:+1: IMHO it will

**Comment by Yourownfont** [comment]
What do you think about:
![image](https://user-images.githubusercontent.com/61000413/110032853-f0693780-7d38-11eb-891b-64375d10cbf4.png)
? Opinions please :)

**Comment by thorn0** [comment]
It's really difficult to say something definite without seeing it in context, in some sample text.

**Comment by dwelle** [comment]
I'd personally prefer the traditional two:

![image](https://user-images.githubusercontent.com/5153846/110154971-2f54c700-7de5-11eb-9f05-115ef8d19ffc.png) ![image](https://user-images.githubusercontent.com/5153846/110154972-311e8a80-7de5-11eb-8fe3-8a73b78acdf7.png) ![image](https://user-images.githubusercontent.com/5153846/110154975-324fb780-7de5-11eb-8a5b-5f8b478e18c6.png) ![image](https://user-images.githubusercontent.com/5153846/110154979-3380e480-7de5-11eb-8df6-2c339458396e.png)

but if we're gonna stick to the curly thing, then it should diagonal should be continuous:

![image](https://user-images.githubusercontent.com/5153846/110155035-4abfd200-7de5-11eb-9987-678beb2f23aa.png)
