### ISSUE TITLE
letter `t` looks like `+`

### ISSUE THREAD

**Issue by dwelle** [excalidraw/virgil#34]
![image](https://user-images.githubusercontent.com/5153846/109494947-e02e2f80-7a8e-11eb-8949-69c34dd2a72f.png)

Above, which is `a+p` and which is `atp`? Answer is: I don't recall.

**Comment by thorn0** [comment]
People really write the t this way, don't they? What problem, exactly, does this create in practice?
Besides, `+` should normally have spaces on both sides.

**Comment by dwelle** [comment]
In practice it makes it pretty much impossible to know whether it's a `t` or a `+`.

Even if from context you can eventually decipher it, it's not a good UX:

![image](https://user-images.githubusercontent.com/5153846/109496100-7e6ec500-7a90-11eb-916b-8909d58fd0d4.png)

Above readers may actually presume you've made a typo.

**Comment by thorn0** [comment]
It's always clear from the context IMHO. Does the fact that the Latin letter O and Cyrillic O look the same is a bad UX?

**Comment by thorn0** [comment]
I found a real-world example where this can be a problem. Formulas like `x = t + 1`

**Comment by dwelle** [comment]
> It's always clear from the context IMHO. Is the fact that the Latin letter O and Cyrillic O look the same a bad UX?

I don't imagine it being a problem since you don't mix Cyrillic and Latin much?

**Comment by thorn0** [comment]
> I don't imagine it being a problem since you don't mix Cyrillic and Latin much?

Exactly. Same with `+`. You normally don't put it in the middle of a word like a letter.

**Comment by anumithaapollo12** [comment]
This is an interesting issue! Can I take it up? :)

**Comment by anumithaapollo12** [comment]
As a user of Excalidraw I have found it difficult to differentiate the two. I would love it if it is modified for better UX. I have attempted in fixing it using FontLab. Let me know what you guys think :)

![Frame 1](https://user-images.githubusercontent.com/38392250/109532481-2c08c500-7adf-11eb-8160-b3e544f795cf.png)

**Comment by dwelle** [comment]
@anumithaapollo12 thanks for helping out! We could also shorten the horizontal line so the vertical one is much taller (I kinda made the vertical one too tall in relation to the other characters):

![image](https://user-images.githubusercontent.com/5153846/109538296-34053c80-7ac0-11eb-8b6d-ab2309103ac4.png)

**Comment by xixixao** [comment]
How I write a lowercase t:

![image](https://user-images.githubusercontent.com/1473433/109538534-40de5c00-7ad1-11eb-8c65-2939d6085327.jpeg)

**Comment by anumithaapollo12** [comment]
@dwelle I thought that it would still look similar. I get what just heightening the length looks like. 
I've tried a couple more iterations based on you're inputs. My personal favourite is the width shortened with left protrude, this way no harm done to the height and we get the looks of lower-case t. Let me know if what you think!

![Frame 2](https://user-images.githubusercontent.com/38392250/109540990-3c25a200-7ae9-11eb-9ffa-bbf4aaad718d.png)

**Comment by thorn0** [comment]
@anumithaapollo12 Would be good to see these variants in context (in words and in formulas). It's difficult to say anything when they're in isolation.

**Comment by dwelle** [comment]
> Would be good to see these variants in context (in words and in formulas). It's difficult to say anything when they're in isolation.

Agreed. In particular, I'd like to try out the last two variants:

![image](https://user-images.githubusercontent.com/5153846/109551419-d2999980-7ad0-11eb-8338-fb67509bc4dc.png)

We need it some playground :)

**Comment by j-f1** [comment]
I think something like this (with a pronounced hook) would make the difference really clear.

<img alt="" width=100 src=https://user-images.githubusercontent.com/25517624/109554345-188b3900-7aa2-11eb-8cb3-f88560da3af0.jpeg>

For example, here is `f` from Virgil flipped vertically:
<img alt="" width=100 src=https://user-images.githubusercontent.com/25517624/109554526-55efc680-7aa2-11eb-9f35-958996f2e7c6.png>

**Comment by anumithaapollo12** [comment]
@thorn0 @dwelle  I'll use it in context to get a clearer picture of the letter!

**Comment by Yourownfont** [comment]
made the + a bit smaller and added a "hook" to the t to clarify

/Ellinor

**Comment by anumithaapollo12** [comment]
@dwelle Here are examples of the last two variants. My personal choice, the second one as it significantly looks like t.
Lemme know what you think!

## Length heightened and width shortened 
<img width="423" alt="Screenshot 2021-03-13 at 4 05 10 PM" src="https://user-images.githubusercontent.com/38392250/111027862-f20dbc00-8418-11eb-8dcf-8d65be286b86.png">

## Width shortened and left protrude
<img width="423" alt="Screenshot 2021-03-13 at 4 23 14 PM" src="https://user-images.githubusercontent.com/38392250/111027865-f3d77f80-8418-11eb-97e7-40ce356ac8e5.png">
