### ISSUE TITLE
Lowercase k too similar to uppercase K

### ISSUE THREAD

**Issue by wietsevenema** [excalidraw/virgil#36]
![image](https://user-images.githubusercontent.com/356014/109548189-9ebc7500-7acc-11eb-8d6a-bf2a22a2a8b5.png)

Make this part a bit smaller? 

![image](https://user-images.githubusercontent.com/356014/109548397-e5aa6a80-7acc-11eb-95fa-4ea1da8a6355.png)

**Comment by dwelle** [comment]
(btw, exporting without background and GitHub dark mode don't go well together :smile:)

**Comment by wietsevenema** [comment]
Whoops. Edited

**Comment by Yourownfont** [comment]
Fixed in next version!
/Ellinor

**Comment by lipis** [comment]
Fixed
