### ISSUE TITLE
Font license

### ISSUE THREAD

**Issue by geraintluff** [excalidraw/virgil#4]
The exported SVGs reference fonts on excalidraw.com.  I'd like to host a copy of the fonts on my domain, but that depends on the license.

I can only see the top-level MIT license - which would be fine to host (with a notice), even for commercial use.  I just wanted to check because I've never seen an MIT-licensed font before, so I got suspicious. 😛

(Side note: I really like the Virgil font, I find it clean and legible, and it made me love Excalidraw immediately.)

**Comment by lipis** [comment]
We went with SIL Open Font License 1.1 and you can read the details here https://github.com/excalidraw/virgil/blob/main/LICENSE.md
