### ISSUE TITLE
Number `7` looks like `1`

### ISSUE THREAD

**Issue by dwelle** [excalidraw/virgil#41]
![image](https://user-images.githubusercontent.com/5153846/109971530-a8292580-7cf6-11eb-9db8-4283e9f6994c.png)

Not sure what to do about it. One way:

![image](https://user-images.githubusercontent.com/5153846/109971567-af503380-7cf6-11eb-99ba-f490dcd56531.png)

Another way is to play with the line inclinations until it looks better.

**Comment by Yourownfont** [comment]
Fixed in next version!

/Ellinor
