### ISSUE TITLE
increase handwritten font number readability

### ISSUE THREAD

**Issue by lein1013** [excalidraw/virgil#45]
Numbers are written slightly different in different languages. 
For the current handwritten numbers 2 and 7 are easy to missread for e.g. german reader

Is there a way to change the font ?
maybe to exchange with the own handwriting http://www.yourfonts.com/

**Comment by dwelle** [comment]
There's an open issue for both 2 (https://github.com/excalidraw/virgil/issues/21) and 7 (https://github.com/excalidraw/virgil/issues/41) digits.

As for supporting custom font, can you open a new issue (in https://github.com/excalidraw/excalidraw/issues)?
