### ISSUE TITLE
The new lowercase t is harder to read

### ISSUE THREAD

**Issue by wietsevenema** [excalidraw/virgil#55]
If think the lowercase t (new version, as in excalidraw+), is harder to read. Here are a few examples: 

- The bottom of the `t` is too high, causing a zig zag
- I think the height should match the `l` and `k`

## The new t
![The new t](https://user-images.githubusercontent.com/356014/117060784-a218ea80-ad21-11eb-8456-b65c5f183e5f.png)

## The old t
![The old t](https://user-images.githubusercontent.com/356014/117060775-9e856380-ad21-11eb-8a39-e761345f1047.png)

**Comment by dwelle** [comment]
The redesign was prompted by the old `t` looking like a `+` (see https://github.com/excalidraw/virgil/issues/34). Good point about the height and the bottom offset.

**Comment by wietsevenema** [comment]
Do you accepts PRs? I would love to contribute a fix to drop the bottom offset at least.

**Comment by thorn0** [comment]
@wietsevenema Of course, we do. Please go ahead.

**Comment by wietsevenema** [comment]
Can you give me some pointers for software to use for the edit?

**Comment by thorn0** [comment]
The software is called [FontLab](https://www.fontlab.com/). Alas, it's neither free nor cheap, but it has a fully functional 30-day trial.
